name: Codestyle

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.14.0
        with:
          php-version: 7.4
          tools: composer

      - name: Install deps
        run: "composer install --prefer-dist --no-progress"

      - name: Linting
        run: "composer linting"

#      - name: Install deps
#        uses: baschny/php-composer-action@v1
#        with: { command: "install --prefer-dist --no-progress" }
#
#      - name: Linting
#        uses: baschny/php-composer-action@v1
#        with: { command: linting }
